//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCMSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int ID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int UserId { get; set; }
        public int StreamID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual User User { get; set; }
        public virtual Scheduler Scheduler { get; set; }
    }
}
